name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.12.0 
        with:
          args: ./...

      - name: Validate Kubernetes Manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: ./k8s

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Trivy for Image Scanning
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scan Docker Image for Vulnerabilities
        run: trivy image ghcr.io/${{ github.repository }}/go-http-server:latest

  docker:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jaycynth/go-http-server:v0.1 .

      - name: Scan Docker image for vulnerabilities
        run: |
          docker run --rm --privileged \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:latest image --exit-code 1 \
          --severity HIGH,CRITICAL \
          jaycynth/go-http-server:v0.1

      - name: Push Docker image
        run: |
          docker push jaycynth/go-http-server:v0.1

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: kind create cluster

      - name: Check Kubernetes cluster status
        run: kubectl cluster-info dump

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/rbac.yaml
          kubectl apply -f k8s/network-policy.yaml
          kubectl apply -f k8s/deployment.yaml
